apiVersion: v1
entries:
  helm_w_cicd:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-25T22:09:16.0136042+02:00"
    description: A demo Helm chart for CI/CD with GitHub Actions
    digest: 7468c2e8b25b86fdef7b95ee146d55089f48383041f6871cc5c508eaef76044a
    name: helm_w_cicd
    type: application
    urls:
    - https://saifkbishi.github.io/helm_w_cicd/helm_w_cicd-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-25T22:09:16.012433+02:00"
